//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VismaLibraryTask.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VismaLibraryTask.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Name&quot;:&quot;Bible&quot;,&quot;Author&quot;:&quot;author1&quot;,&quot;Category&quot;:&quot;prayer&quot;,&quot;Language&quot;:&quot;english&quot;,&quot;PublicationDate&quot;:&quot;2012-01-01T00:00:00&quot;,&quot;ISBN&quot;:&quot;0-000-000-000-001&quot;,&quot;Taken&quot;:false,&quot;TakenBy&quot;:null,&quot;TakenUntil&quot;:null},{&quot;Name&quot;:&quot;Test&quot;,&quot;Author&quot;:&quot;author&quot;,&quot;Category&quot;:&quot;testing&quot;,&quot;Language&quot;:&quot;English&quot;,&quot;PublicationDate&quot;:&quot;2000-01-01T00:00:00&quot;,&quot;ISBN&quot;:&quot;0-000-000-000-002&quot;,&quot;Taken&quot;:true,&quot;TakenBy&quot;:&quot;Jonas&quot;,&quot;TakenUntil&quot;:&quot;2021-08-10T13:59:47.3070187+03:00&quot;},{&quot;Name&quot;:&quot;a&quot;,&quot;Author&quot;:&quot;a&quot;,&quot;Category&quot;:&quot;a&quot;,&quot;Language&quot;:&quot;a&quot;,&quot;PublicationDate&quot;:&quot;2020-02-02T00:00:00&quot;,&quot;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bookFile {
            get {
                return ResourceManager.GetString("bookFile", resourceCulture);
            }
        }
    }
}
